---
--- Generated by Luanalysis
--- Created by 22511.
--- DateTime: 2023/2/25 11:00
---
local voucherId = ARGV[1];

--用户key
local userId = ARGV[2];

-- 数据key
--库存key
local stockKey = 'stock:vid:' .. voucherId;
--订单key
local orderKey = 'seckill:vid:' .. voucherId;


if(tonumber(redis.call('get',stockKey)) <= 0) then
    --库存不足，返回 1
    return 1;
end
--判断用户是否重复下单(订单中存在userId):  sismember命令判断成员元素是否是集合的成员。
if(redis.call('sismember',orderKey,userId) == 1) then
--    存在，说明重复下单，返回2
    return 2;
end
--扣减库存
redis.call('incrby',stockKey,-1);
--下单 将userId存入当前优惠卷set集合中，返回0
redis.call('sadd',orderKey,userId);
return 0;